-- MySQL Script generated by MySQL Workbench
-- Model: FanChat Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fanchat
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `fanchat` DEFAULT CHARACTER SET utf8 ;
USE `fanchat` ;

-- -----------------------------------------------------
-- Table `fanchat`.`usuario_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fanchat`.`usuario_chat` (
  `idusuario_chat` CHAR(36) NOT NULL,               -- UUID como chave primária
  PRIMARY KEY (`idusuario_chat`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `fanchat`.`logs_usuarios_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fanchat`.`logs_usuarios_chat` (
  `idlogs_usuario_chat` CHAR(36) NOT NULL,          -- UUID como chave primária do log
  `character_name` VARCHAR(255) NOT NULL,
  `message` LONGTEXT NOT NULL,
  `response_chat` LONGTEXT NOT NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_chat_idusuario_chat` CHAR(36) NOT NULL,  -- UUID como chave estrangeira
  PRIMARY KEY (`idlogs_usuario_chat`),
  INDEX `fk_logs_usuarios_chat_usuario_chat_idx` (`usuario_chat_idusuario_chat` ASC),
  CONSTRAINT `fk_logs_usuarios_chat_usuario_chat`
    FOREIGN KEY (`usuario_chat_idusuario_chat`)
    REFERENCES `fanchat`.`usuario_chat` (`idusuario_chat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
